### ISSUE TITLE
Transliterate from Latin to Thaana

### ISSUE THREAD

**Issue by viktormorales** [naxeem/thaana-transliterator#5]
Hi,

Before my question I would like to thank you for this class. Works great!

Is there a way to transliterate from Latin to Thaana?

Thanks in advance.

**Comment by naxeem** [comment]
Hi,

I don't know of any such scripts. 

Thank you :)

**Comment by boring-dragon** [comment]
> Hi,
> 
> Before my question I would like to thank you for this class. Works great!
> 
> Is there a way to transliterate from Latin to Thaana?
> 
> Thanks in advance.

I think you can reverse engineer this class in a way to make it work maybe. 
checkout https://github.com/jawish/thaana_conversions_php
